### ISSUE TITLE
Should we add the official license?

### ISSUE THREAD

**Issue by dorukozturk** [girder/cookiecutter-girder-plugin#1]
@jbeezley Should we change the cookiecutter to add https://github.com/girder/girder/blob/master/LICENSE?

**Comment by jbeezley** [comment]
It does contain a [shorter version](https://github.com/girder/cookiecutter-girder-plugin/blob/master/%7B%7Bcookiecutter.package_name%7D%7D/LICENSE) of that same license that links to the full version...  I have no idea what is preferred.
